export interface clienteSocieta {
    idcliente: number | null,
    ragionesociale: string,
    partitaiva: string,
    sedelegale?: string | null,
    sedeoperativa?: string | null,
    patinail: string,
    rappresentantelegale?: string | null,
    sedelavoro?: string,
    codiceateco?: string | null,
    numerotelefono?: string | null,
    indirizzopec?: string | null,
    refamministratore?: string | null,
    emailrefammin?: string | null,
    telefonorefammin?: string | null,
}